<?php

namespace App\Service;

use App\Entity\ExportJob;
use App\Entity\MigrationBatch;
use App\Entity\MigrationRow;
use App\Enum\ExportKind;
use App\Message\GenerateCardExport;
use App\Repository\MigrationRowRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Messenger\MessageBusInterface;

/**
 * The two exports queued when a batch that skipped rows to correct completes: the rows it replaced
 * in core, and the rows it left out in the upload format (fix them and upload the file again).
 * They are ordinary export jobs, generated by the worker and offered on the Exports page.
 */
final class BatchReportExport
{
    public const MIGRATED_HEADER = ['card_ref', 'card_number', 'cardholder', 'old_account', 'new_account', 'linked_cards', 'applied_at', 'approved_by'];
    /** The upload format; the line and errors columns are ignored on upload. */
    public const CORRECTIONS_HEADER = ['card_ref', 'current_account', 'new_account', 'line', 'errors'];
    /** Accounts a rollback left on their new number: current_account is the old number it could not get back. */
    public const ROLLBACK_SKIPPED_HEADER = ['card_ref', 'old_account', 'new_account', 'line', 'reason'];
    private const SKIPPED = 'Skipped: another row of this account needs correction.';

    public function __construct(
        private readonly MigrationRowRepository $rows,
        private readonly EntityManagerInterface $em,
        private readonly MessageBusInterface $bus,
        private readonly CsvResponseFactory $csv,
        private readonly Filesystem $filesystem,
    ) {
    }

    /** @return list<ExportJob> the migrated-rows job, then the rows-to-correct job */
    public function queue(MigrationBatch $batch, string $requestedBy): array
    {
        $applied = $this->rows->countApplied($batch);
        $jobs = [
            new ExportJob($requestedBy, null, $applied, ExportKind::BatchMigrated, $batch),
            new ExportJob($requestedBy, null, $batch->getRowCount() - $applied, ExportKind::BatchCorrections, $batch),
        ];
        array_map($this->em->persist(...), $jobs);
        $this->em->flush();
        foreach ($jobs as $job) {
            $this->bus->dispatch(new GenerateCardExport($job->getId()));
        }

        return $jobs;
    }

    /** Queues the export of the accounts a rollback had to leave alone (only when there are any). */
    public function queueRollbackSkipped(MigrationBatch $batch, string $requestedBy, int $rows): ExportJob
    {
        $job = new ExportJob($requestedBy, null, $rows, ExportKind::BatchRollbackSkipped, $batch);
        $this->em->persist($job);
        $this->em->flush();
        $this->bus->dispatch(new GenerateCardExport($job->getId()));

        return $job;
    }

    /**
     * Writes $job's report to $path. The file only appears under its final name once complete.
     *
     * @param callable(int, int): void $onChunk called every 1,000 rows (and at the end) with the rows written
     */
    public function writeFile(ExportJob $job, string $path, callable $onChunk): void
    {
        $batch = $job->getBatch() ?? throw new \LogicException(sprintf('Export #%d is not about a batch.', $job->getId()));
        [$header, $filter, $line] = match ($job->getKind()) {
            ExportKind::BatchMigrated => [self::MIGRATED_HEADER, 'applied', fn (MigrationRow $r) => $this->migrated($r, $batch)],
            ExportKind::BatchRollbackSkipped => [self::ROLLBACK_SKIPPED_HEADER, 'rollback_skipped', static fn (MigrationRow $r) => [$r->getCardRef(), $r->getCurrentAccount(), $r->getNewAccount(), (string) $r->getLineNumber(), $r->getRollbackError()]],
            default => [self::CORRECTIONS_HEADER, 'pending', $this->correction(...)],
        };

        $this->filesystem->mkdir(\dirname($path));
        $partial = $path.'.part';
        $handle = fopen($partial, 'w');
        try {
            $this->csv->writeRow($handle, $header);
            $written = 0;
            foreach ($this->rows->stream($batch, $filter) as $row) {
                $this->csv->writeRow($handle, $line($row));
                if (0 === ++$written % 1000) {
                    $onChunk(1000, 1000);
                }
            }
            if (0 !== $written % 1000) {
                $onChunk($written % 1000, $written % 1000);
            }
        } catch (\Throwable $e) {
            fclose($handle);
            $this->filesystem->remove($partial);
            throw $e;
        }
        fclose($handle);
        $this->filesystem->rename($partial, $path, true);
    }

    /** @return list<?string> */
    private function migrated(MigrationRow $row, MigrationBatch $batch): array
    {
        return [$row->getCardRef(), $row->getCardDisplay(), $row->getCardholder(), $row->getCurrentAccount(), $row->getNewAccount(),
            (string) $row->getLinkedCards(), $row->getAppliedAt()?->format(\DATE_ATOM), $batch->getReviewedBy()];
    }

    /** @return list<?string> */
    private function correction(MigrationRow $row): array
    {
        $errors = implode(' ', $row->getErrors());

        return [$row->getCardRef(), $row->getCurrentAccount(), $row->getNewAccount(), (string) $row->getLineNumber(), '' === $errors ? self::SKIPPED : $errors];
    }
}
