<?php

namespace App\Entity;

use App\Enum\ExportState;
use App\Repository\ExportJobRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * A card-account source export too large to download in one request; generated by the messenger worker.
 */
#[ORM\Entity(repositoryClass: ExportJobRepository::class)]
class ExportJob
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 16, enumType: ExportState::class)]
    private ExportState $state = ExportState::Queued;

    #[ORM\Column]
    private int $rowsWritten = 0;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $finishedAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $error = null;

    public function __construct(
        #[ORM\Column(length: 180)]
        private string $requestedBy,
        /** Only cards with this status description; null = all cards. */
        #[ORM\Column(length: 100, nullable: true)]
        private ?string $statusFilter,
        /** Row estimate at request time (from the cached status counts), for the progress bar. */
        #[ORM\Column]
        private int $expectedRows,
    ) {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function start(): void
    {
        $this->state = ExportState::Running;
    }

    public function addRows(int $count): void
    {
        $this->rowsWritten += $count;
    }

    public function complete(): void
    {
        $this->state = ExportState::Completed;
        $this->finishedAt = new \DateTimeImmutable();
    }

    /** The file was removed after the retention period; the job stays listed for the record. */
    public function expire(): void
    {
        $this->state = ExportState::Expired;
    }

    public function fail(string $error): void
    {
        $this->state = ExportState::Failed;
        $this->finishedAt = new \DateTimeImmutable();
        $this->error = $error;
    }

    /** Percentage for the progress bar; capped at 99 until the job is actually done. */
    public function progress(): int
    {
        if (ExportState::Completed === $this->state) {
            return 100;
        }

        return $this->expectedRows > 0 ? min(99, (int) floor($this->rowsWritten / $this->expectedRows * 100)) : 0;
    }

    public function downloadName(): string
    {
        $suffix = $this->statusFilter ? '-'.strtolower(trim((string) preg_replace('/[^A-Za-z0-9]+/', '-', $this->statusFilter), '-')) : '';

        return sprintf('card-account-source%s-%d.csv', $suffix, $this->id);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getState(): ExportState
    {
        return $this->state;
    }

    public function getRequestedBy(): string
    {
        return $this->requestedBy;
    }

    public function getStatusFilter(): ?string
    {
        return $this->statusFilter;
    }

    public function getExpectedRows(): int
    {
        return $this->expectedRows;
    }

    public function getRowsWritten(): int
    {
        return $this->rowsWritten;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getFinishedAt(): ?\DateTimeImmutable
    {
        return $this->finishedAt;
    }

    public function getError(): ?string
    {
        return $this->error;
    }
}
